### PR TITLE
Builds on modern Ubuntu

### PR DESCRIPTION
**Pull request by RobertLarsen**
This makes sasquatch build on Ubuntu 22.04

### CODE REVIEW

**Comment by ladbsoft** [comment]
Tested and working in Ubuntu 22.10 with gcc 11.4.0.

Hopefully the owner notices and this gets merged. Thanks, mate!

**Comment by 0xdead8ead** [comment]
Came here because of this error during compilation on Ubuntu 22.04:

```
cc -g -O2  -I. -I./LZMA/lzma465/C -I./LZMA/lzmalt -I./LZMA/lzmadaptive/C/7zip/Compress/LZMA_Lib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DCOMP_DEFAULT=\"gzip\" -Wall -Werror  -DGZIP_SUPPORT -DLZMA_SUPPORT -DXZ_SUPPORT -DLZO_SUPPORT -DXATTR_SUPPORT -DXATTR_DEFAULT   -c -o unsquashfs.o unsquashfs.c
unsquashfs.c: In function 'read_super':
unsquashfs.c:1835:5: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
 1835 |     if(swap)
           |     ^~
unsquashfs.c:1841:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
      |         read_fs_bytes(fd, SQUASHFS_START, sizeof(struct squashfs_super_block),
      |         ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [<builtin>: unsquashfs.o] Error 1

```

The above PR works for `ubuntu:22.04`. Thanks @RobertLarsen !!

For those waiting for this to be merged, for now you can do:
```
git clone https://github.com/devttys0/sasquatch
(cd sasquatch && git pull origin pull/56/head && ./build.sh)
```

**Comment by leoss** [comment]
This also works on Ubuntu 23.04.

**Comment by matteius** [comment]
To build on Ubuntu 24.10:

Clone @RobertLarsen 's branch 
Run `./build.sh` to apply patches
`cd squashfs4.3/squashfs-tools/`
`vim Makefile`
Add `-Wno-error` to the CLFAGS line (pick one)
run `make` in that directory
`sudo cp sasquatch /usr/local/bin`

should be available after that

**Comment by RobertLarsen** [comment]
These changes make sasquatch build on modern Ubuntus

**Comment by RickzDO** [comment]
still lots of compiltations error on ubuntu 24.04, not working

**Comment by RobertLarsen** [comment]
@RickzDO What errors do you see?

I use the following script for testing and get no errors on Ubuntu 24.04:

```
#!/bin/bash

apt update && \
    apt -y install wget && \
    (yes | ./build.sh) && \
    sasquatch -v
```

I use the following command for running the test script:

```
$ docker run --rm -it -v $(pwd):/host --workdir /host ubuntu:24.04 ./test.sh
```

**Comment by RickzDO** [comment]
> @RickzDO What errors do you see?
> 
> I use the following script for testing and get no errors on Ubuntu 24.04:
> 
> ```
> #!/bin/bash
> 
> apt update && \
>     apt -y install wget && \
>     (yes | ./build.sh) && \
>     sasquatch -v
> ```
> 
> I use the following command for running the test script:
> 
> ```
> $ docker run --rm -it -v $(pwd):/host --workdir /host ubuntu:24.04 ./test.sh
> ```

i believe the instructions i fallowed gets wrong at some point browsing directories or wrong path by the scripts, checked there was 2 directories with build.sh , at the end copied modified squash-tools dir one level up of squash directory and ran build again , gave some errors but the compilation finally was success, cos still was failing with latest Kali Linux , is hard to believe Kali don't have binwall full working , will try later again on unbuntu 24.04 LTS noble , if someone wants to check this, just let me know, i have the console of logs/inputs i did and complete folders structure zipped, i fallowed this info:  hxxps://www.linkedin.com/pulse/building-sasquatch-ubuntu-2404-daniel-darby-6ebie/

**Comment by RickzDO** [comment]
made an automated script to install sasquatch + binwalk 3.1 , succesfully installed!!! feel free to make improvements if needed
tested with ubuntu 24.04 lts noble here: https://github.com/RickzDO/Installer_script_Binwalk3.1_sasquatch4.3 
should i use latest sasquatch 4.7 ? anyone knows if better ?

**Comment by Kungergely** [comment]
> 
> For those waiting for this to be merged, for now you can do:
> 
> ```
> git clone https://github.com/devttys0/sasquatch
> (cd sasquatch && git pull origin pull/56/head && ./build.sh)
> ```

I can confirm that this method works on Ubuntu 24.04 as well, thanks.
